paths:
  /makechart-inspect:
    get:
      produces:
        - image/png
      responses:
        200:
          description: Success
          schema:
            type: file
  /makechart-generate:
    post:
      produces:
        - image/png
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/CommonRequest"
      responses:
        200:
          description: Success
          schema:
            type: file